### ISSUE TITLE
Is there a reason to continue to maintain MR and non MR versions?

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-teamwork-MR#20]
The MR version has more functionality at this point, so should we just focus on that?

**Comment by dhmspector** [comment]
the non-MR one is a branch of the private repo in the main Realm GitHub repo - there are a couple of things that are WIPs for this version that aren't yet ready to be public (i.e., not finished) and since there's no way to have a split public/private repo they're still over there for the moment.

**Comment by dhmspector** [comment]
the old non-MR version has been deleted; this repo will maintain pointers/tags for the MR version as well as the new partial sync version.
