### ISSUE TITLE
Guard against unwrapping nil values

### ISSUE THREAD

**Issue by ianpward** [realm/realm-teamwork-MR#30]
I am getting crashes when trying to unwrap null values - we should not allow tasks to be added that are null

![image](https://user-images.githubusercontent.com/1691481/26985337-eeddb802-4cf7-11e7-8fe5-cb561769f596.png)

![image](https://user-images.githubusercontent.com/1691481/26985418-4fe22f84-4cf8-11e7-8f45-7e573a5d235f.png)

@bigfish24 @dhmspector

**Comment by dhmspector** [comment]
fixed
